learn_type: 'on_policy'
action_select: 'sample'  # sample, distribution
algo_type: 'value_based'  # value_based, policy_based
obs_list: []
reward_list: []
metric_list: []
reward_weight: []
epochs: 1
episodes: 200
max_episode_len: 3600
network_structure: 'no_share'
batch_size: 128
hidden_dim: 128
activate_fn: 'None'
buffer_size: 1e6
gamma: 0.99
tau: 5e-5
critic_lr: 4e-4
actor_lr: 5e-4
update_step: 100 